activation: gelu
attn: full
batch_size: 128
c_out: 1
cols:
- XOM_logpctchange
- CVX_logpctchange
- COP_logpctchange
- BP_logpctchange
- PBR_logpctchange
- WTI_logpctchange
- EOG_logpctchange
- ENB_logpctchange
- SLB_logpctchange
d_ff: 4096 #2048
d_model: 512
data_path: full_1h.csv
date_end: '2020-01-01'
date_start: '2012-01-01'
date_test: '2019-06-01'
des: full_1h
distil: false
dont_shuffle_train: true
dropout: 0.5
dropout_emb: 0.0
e_layers: 12
emb_t2v_app_dim: 16
embed: time2vec_app
enc_in: 9
factor: 5
features: MS
freq: h
inverse_output: false
inverse_pred: true
label_len: 0
learning_rate: 1.0e-05
ln_mode: post
loss: stock_tanhv1
lradj: type3
mix: false
model: stockformer
n_heads: 512
no_early_stop: false
no_scale_mean: true
optim: AdamW
output_attention: false
patience: 100
pred_len: 1
root_path: ./data/stock/
scale: true
seed: null
seq_len: 16
target: WTI_logpctchange
max_epochs: 20
